### ISSUE TITLE
Java.Lang.NoClassDefFoundError for com/mapbox/turf/TurfMeasurement.

### ISSUE THREAD

**Issue by yero007** [NAXAM/xam-mapbox-android#31]
Android API:

compileSdkVersion 30
targetSdkVersion 30

Hi,

When I enable the location component it's throwing a Java.Lang.NoClassDefFoundError for com/mapbox/turf/TurfMeasurement.

`[AppCenterCrashes] Unhandled Exception from source=AndroidEnvironment
[AppCenterCrashes] Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/turf/TurfMeasurement; ---> Java.Lang.ClassNotFoundException: Didn't find class "com.mapbox.turf.TurfMeasurement" on path: DexPathList[[zip file "/data/app/~~u6LdxVZAj4IUBR1Sqzjs4w==/com.deventure.curier_android-SLF6i1BZPBRq2YzOEvZxAg==/base.apk"],nativeLibraryDirectories=[/data/app/~~u6LdxVZAj4IUBR1Sqzjs4w==/com.deventure.curier_android-SLF6i1BZPBRq2YzOEvZxAg==/lib/arm64, /data/app/~~u6LdxVZAj4IUBR1Sqzjs4w==/com.deventure.curier_android-SLF6i1BZPBRq2YzOEvZxAg==/base.apk!/lib/arm64-v8a, /system/lib64]]
[AppCenterCrashes]    --- End of inner exception stack trace ---
[AppCenterCrashes]   at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <94b04e1756104d1fa1d144932ae2720c>:0 
[AppCenterCrashes]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <94b04e1756104d1fa1d144932ae2720c>:0 
[AppCenterCrashes]   at Com.Mapbox.Mapboxsdk.Location.LocationComponent.set_LocationComponentEnabled (System.Boolean value) [0x00018] in /Volumes/ws/libs/mapbox-android-binding/generated/com.mapbox.mapboxsdk.mapbox-android-sdk/obj/Release/monoandroid90/generated/src/Com.Mapbox.Mapboxsdk.Location.LocationComponent.cs:158 
[AppCenterCrashes]   at Curier.Android.UI.Fragments.MapFragment.OnStyleLoaded (Com.Mapbox.Mapboxsdk.Maps.Style p0) [0x00046] in /Volumes/T7/Projects/CautCurier/Curier.Mobile/Curier/Curier.Android/UI/Fragments/MapFragment.cs:97 
[AppCenterCrashes]   at Com.Mapbox.Mapboxsdk.Maps.Style+IOnStyleLoadedInvoker.n_OnStyleLoaded_Lcom_mapbox_mapboxsdk_maps_Style_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_p0) [0x00010] in /Volumes/ws/libs/mapbox-android-binding/generated/com.mapbox.mapboxsdk.mapbox-android-sdk/obj/Release/monoandroid90/generated/src/Com.Mapbox.Mapboxsdk.Maps.Style.cs:1780 
[AppCenterCrashes]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.80(intptr,intptr,intptr)
[AppCenterCrashes]   --- End of managed Java.Lang.NoClassDefFoundError stack trace ---
[AppCenterCrashes] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/turf/TurfMeasurement;
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.geometry.LatLng.distanceTo(LatLng.java:328)
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.location.Utils.immediateAnimation(Utils.java:107)
[AppCenterCrashes]   at Com.Mapbox.Mapboxsdk.Maps.St08-27 15:05:22.914 E/AppCenterCrashes(15744): 	at com.mapbox.mapboxsdk.location.LocationAnimatorCoordinator.feedNewLocation(LocationAnimatorCoordinator.java:93)
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.location.LocationComponent.updateLocation(LocationComponent.java:1444)
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.location.LocationComponent.updateLocation(LocationComponent.java:1411)
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.location.LocationComponent.access$1000(LocationComponent.java:98)
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.location.LocationComponent$LastLocationEngineCallback.onSuccess(LocationComponent.java:1650)
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.location.LocationComponent$LastLocationEngineCallback.onSuccess(LocationComponent.java:1638)
[AppCenterCrashes] 	at com.mapbox.m.914 E/AppCenterCrashes(15744): 	at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.getLastLocation(MapboxFusedLocationEngineImpl.java:39)
[AppCenterCrashes] 	at com.mapbox.android.core.location.LocationEngineProxy.getLastLocation(LocationEngineProxy.java:25)
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.location.LocationComponent.setLastLocation(LocationComponent.java:1480)
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1271)
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.location.LocationComponent.enableLocationComponent(LocationComponent.java:1387)
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.location.LocationComponent.setLocationComponentEnabled(LocationComponent.java:516)
[AppCenterCrashes] 	at MapFragment.n_onStyleLoaded(Native Method)
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:959)
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:221)
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1328)
[AppCenterCrashes] 	at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
[AppCenterCra08-27 15:05:22.914 E] 	at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1106)
[AppCenterCrashes] 	at android.os.MessageQueue.nativePollOnce(Native Method)
[AppCenterCrashes] 	at android.os.MessageQueue.next(MessageQueue.java:335)
[AppCenterCrashes] 	at android.app.ActivityThread.main(ActivityThread.java:8512)
[AppCenterCrashes] 	at java.lang.reflect.Method.invoke(Native Method)
[AppCenterCrashes] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
[AppCenterCrashes] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
[AppCenterCrashes] Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.turf.TurfMeasurement" on path: DexPathList[[zip file "/data/app/~~u6LdxVZAj4IUBR1Sqzjs4w==/com.deventure.curier_android-SLF6i1BZPBRq2YzOEvZxAg==/base.apk"],nativeLibraryDirectories=[/data/app/~~u6LdxVZAj4IUBR1Sqzjs4w==/com.deventure.curier_android-SLF6i1BZPBRq2YzOEvZxAg==/lib/arm64, /data/app/~~u6LdxVZAj4IUBR1Sqzjs4w==/com.deventure.curier_android-SLF6i1BZPBRq2YzOEvZxAg==/base.apk!/lib/arm64-v8a, /system/lib64]]
[AppCen08-27 15:05:22.914 E] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[AppCenterCrashes] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[AppCenterCrashes] 	... 29 more`

Has anyone encountered this error? 
Thank you!

**Comment by sergsel** [comment]
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: net.triphub.transport.barcelona, PID: 24345
[AndroidRuntime] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/turf/TurfMeasurement;
[AndroidRuntime] 	at com.mapbox.mapboxsdk.geometry.LatLng.distanceTo(LatLng.java:328)
[AndroidRuntime] 	at com.mapbox.mapboxsdk.location.Utils.immediateAnimation(Utils.java:107)
[AndroidRuntime] 	at com.mapbox.mapboxsdk.location.LocationAnimatorCoordinator.feedNewLocation(LocationAnimatorCoordinator.java:124)
[AndroidRuntime] 	at com.mapbox.mapboxsdk.location.LocationAnimatorCoordinator.feedNewLocation(LocationAnimatorCoordinator.java:93)
[AndroidRuntime] 	at com.mapbox.mapboxsdk.location.LocationComponent.updateLocation(LocationComponent.java:1444)
[AndroidRuntime] 	at com.mapbox.mapboxsdk.location.LocationComponent.updateLocation(LocationComponent.java:1411)
[AndroidRuntime] 	at com.mapbox.mapboxsdk.location.LocationComponent.access$1000(LocationComponent.java:98)
[AndroidRuntime] 	at com.mapbox.mapboxsdk.location.LocationComponent$LastLocationEngineCallback.onSuccess(LocationComponent.java:1650)
[AndroidRuntime] 	at com.mapbox.mapboxsdk.location.LocationComponent$LastLocationEngineCallback.onSuccess(LocationComponent.java:1638)
[AndroidRuntime] 	at com.mapbox.android.core.location.GoogleLocationEngineImpl$GoogleLastLocationEngineCallbackTransport.onSuccess(GoogleLocationEngineImpl.java:136)
[AndroidRuntime] 	at com.mapbox.android.core.location.GoogleLocationEngineImpl$GoogleLastLocationEngineCallbackTransport.onSuccess(GoogleLocationEngineImpl.java:125)
[AndroidRuntime] 	at com.google.android.gms.tasks.zzj.run(Unknown Source:27)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:938)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:236)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:8061)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
[AndroidRuntime] Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.turf.TurfMeasurement" on path: DexPathList[[zip file "/data/app/~~TZ5_w2WxYx2RKEBhthsWIA==/net.triphub.transport.barcelona-iGhZZkY4auoYDlLLcYDFvQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~TZ5_w2WxYx2RKEBhthsWIA==/net.triphub.transport.barcelona-iGhZZkY4auoYDlLLcYDFvQ==/lib/arm64, /data/app/~~TZ5_w2WxYx2RKEBhthsWIA==/net.triphub.transport.barcelona-iGhZZkY4auoYDlLLcYDFvQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /system/product/lib64]]
[AndroidRuntime] 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[AndroidRuntime] 	... 19 more
[OOMEventManagerFK] checkEventAndDumpForJE: 0
**Java.Lang.NoClassDefFoundError:** 'Failed resolution of: Lcom/mapbox/turf/TurfMeasurement;'

**Comment by tuyen-vuduc** [comment]
Please check out latest version. https://www.nuget.org/packages/Com.Mapbox.Maps.Android
